//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hand
    {
        public int idHand { get; set; }
        public Nullable<int> idCard { get; set; }
        public int idUser { get; set; }
        public int quantity { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual Users Users { get; set; }
    }
}
