//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoatverseEntities : DbContext
    {
        public GoatverseEntities()
            : base("name=GoatverseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Blocked> Blocked { get; set; }
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
