//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoatverseEntities : DbContext
    {
        public GoatverseEntities()
            : base("name=GoatverseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cards> Cards { get; set; }
        public virtual DbSet<Hand> Hand { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<PlayerActions> PlayerActions { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
