//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerActions
    {
        public int idAction { get; set; }
        public Nullable<int> idUser { get; set; }
        public string actionDescription { get; set; }
        public Nullable<System.DateTime> actionTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
