//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerActions
    {
        public int idAction { get; set; }
        public Nullable<int> idUser { get; set; }
        public string actionDescription { get; set; }
        public Nullable<System.DateTime> actionTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
