//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int idProfile { get; set; }
        public Nullable<int> profileLevel { get; set; }
        public Nullable<int> totalPoints { get; set; }
        public Nullable<int> matchesWon { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> imageId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
