//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int idProfile { get; set; }
        public Nullable<int> profileLevel { get; set; }
        public Nullable<int> totalPoints { get; set; }
        public Nullable<int> matchesWon { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
